-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--

-- local frcpal = require("frcpal")
--
-- vim.keymap.set("n", "<leader>pb", function()
--   frcpal.gradle("build")
-- end, { desc = "build" }) -- pb for Project Build
-- vim.keymap.set("n", "<leader>pd", function()
--   frcpal.gradle("deploy")
-- end, { desc = "deploy" }) -- pd for Project Deploy
-- vim.keymap.set("n", "<leader>pD", frcpal.get_vendorde, { desc = "vendordep" }) -- pD for Project Dependencies
