#!/usr/bin/env fish
#
# theme.fish — central base16 theme engine
#
# One base16 palette drives colors for every configurable app.
# Palettes live in ~/.config/themes/palettes/<name>.conf (key=value, base00..base0F).
#
# Usage:
#   theme.fish apply <name>     render every app from palette <name> and reload
#   theme.fish current          print the active theme name
#   theme.fish list             list available palettes (one per line)
#   theme.fish matugen [image]  generate a palette from an image (or current wallpaper)
#                               with matugen, then apply it
#
# Managed regions in existing config files are delimited with theme-manager
# markers so this script is idempotent and never clobbers your other settings.

set -g THEMES_DIR "$HOME/.config/themes"
set -g PALETTE_DIR "$THEMES_DIR/palettes"
set -g CFG "$HOME/.config"

# ---------------------------------------------------------------------------
# palette loading
# ---------------------------------------------------------------------------

# Reads a palette file into P_* global variables (P_name, P_mode, P_base00 ...).
function load_palette --argument-names file
    set -e P_name P_mode
    for k in base00 base01 base02 base03 base04 base05 base06 base07 \
             base08 base09 base0A base0B base0C base0D base0E base0F
        set -g P_$k ""
    end
    set -g P_mode dark
    for line in (cat $file)
        set line (string trim -- $line)
        test -z "$line"; and continue
        string match -q '#*' -- $line; and continue
        set -l kv (string split -m1 '=' -- $line)
        test (count $kv) -eq 2; or continue
        set -g P_(string trim -- $kv[1]) (string trim -- $kv[2])
    end
    test -n "$P_name"; or set -g P_name (basename $file .conf)
end

# Scales an RRGGBB hex by a factor (>1 lightens, <1 darkens), clamped to ff.
# Used to derive surfaces that stay monotonic on palettes that aren't.
function shade_hex --argument-names hex factor
    awk -v h=$hex -v f=$factor 'BEGIN{
        r=strtonum("0x"substr(h,1,2)); g=strtonum("0x"substr(h,3,2)); b=strtonum("0x"substr(h,5,2));
        r=int(r*f+0.5); g=int(g*f+0.5); b=int(b*f+0.5);
        if(r>255)r=255; if(g>255)g=255; if(b>255)b=255;
        printf "%02x%02x%02x", r,g,b
    }'
end

# ---------------------------------------------------------------------------
# renderers
# ---------------------------------------------------------------------------

function _foot_colors
    printf 'alpha=0.92\nforeground=%s\nbackground=%s\n' $P_base05 $P_base00
    printf 'regular0=%s\nregular1=%s\nregular2=%s\nregular3=%s\n' $P_base00 $P_base08 $P_base0B $P_base0A
    printf 'regular4=%s\nregular5=%s\nregular6=%s\nregular7=%s\n' $P_base0D $P_base0E $P_base0C $P_base05
    printf 'bright0=%s\nbright1=%s\nbright2=%s\nbright3=%s\n' $P_base03 $P_base08 $P_base0B $P_base0A
    printf 'bright4=%s\nbright5=%s\nbright6=%s\nbright7=%s\n' $P_base0D $P_base0E $P_base0C $P_base07
    printf 'selection-foreground=%s\nselection-background=%s\n' $P_base05 $P_base02
end

function render_foot
    set -l f "$CFG/foot/foot.ini"
    test -f $f; or return
    # keep everything except any [colors*] section, then append fresh ones.
    # foot 1.27 wants [colors-dark]/[colors-light] (bare [colors] is deprecated);
    # we write the active theme into both so foot always matches regardless of
    # its light/dark preference.
    awk '
      /^\[colors/ {skip=1; next}
      /^\[/       {skip=0}
      skip==0     {print}
    ' $f | string collect | string trim -r >$f.tmp
    begin
        printf '\n\n[colors-dark]\n'
        _foot_colors
        printf '\n[colors-light]\n'
        _foot_colors
    end >>$f.tmp
    mv $f.tmp $f
end

function render_fuzzel
    set -l f "$CFG/fuzzel/fuzzel.ini"
    test -f $f; or return
    awk '
      /^\[colors/ {skip=1; next}
      /^\[/       {skip=0}
      skip==0     {print}
    ' $f | string collect | string trim -r >$f.tmp
    printf '\n\n# generated by theme.fish — %s\n[colors]\n' $P_name >>$f.tmp
    printf 'background=%sf2\ntext=%sff\nprompt=%sff\ninput=%sff\n' $P_base00 $P_base05 $P_base05 $P_base05 >>$f.tmp
    printf 'match=%sff\nselection=%sff\nselection-text=%sff\nselection-match=%sff\n' $P_base0D $P_base02 $P_base05 $P_base0D >>$f.tmp
    printf 'border=%sff\ncounter=%sff\nplaceholder=%sff\n' $P_base0D $P_base04 $P_base04 >>$f.tmp
    mv $f.tmp $f
end

function render_waybar
    set -l f "$CFG/waybar/theme.css"
    # Depth ladder derived from base00 so it stays monotonic on every theme
    # (base16 palettes aren't reliably ordered). Reproduces the original
    # crust<mantle<base<surface0 layering: bar is darkest, modules step up.
    # Dark themes step lighter toward the centre; light themes reverse.
    set -l f_darker; set -l f_dark; set -l f_light
    if test "$P_mode" = light
        set f_darker 0.93; set f_dark 0.97; set f_light 0.88
    else
        set f_darker 0.62; set f_dark 0.80; set f_light 1.55
    end
    begin
        printf '/* generated by theme.fish — %s (%s) */\n\n' $P_name $P_mode
        # raw base16
        for k in base00 base01 base02 base03 base04 base05 base06 base07 \
                 base08 base09 base0A base0B base0C base0D base0E base0F
            printf '@define-color %s #%s;\n' $k (eval echo \$P_$k)
        end
        printf '\n/* depth tiers derived from base00 (mode-aware) */\n'
        printf '@define-color tier_darker shade(@base00, %s);\n' $f_darker
        printf '@define-color tier_dark   shade(@base00, %s);\n' $f_dark
        printf '@define-color tier_mid    @base00;\n'
        printf '@define-color tier_light  shade(@base00, %s);\n' $f_light
        printf '\n/* main */\n'
        printf '@define-color accent   #%s;\n' $P_base0D
        printf '@define-color main-br  #%s;\n' $P_base04
        printf '@define-color main-bg  @tier_darker;\n'
        printf '@define-color main-fg  #%s;\n' $P_base05
        printf '@define-color hover-bg @tier_mid;\n'
        printf '@define-color hover-fg alpha(@main-fg, 0.75);\n'
        printf '@define-color outline  shade(@main-bg, 0.5);\n'
        printf '\n/* modules (mid=base, dark=recessed, light=raised centre) */\n'
        printf '@define-color workspaces  @tier_mid;\n'
        printf '@define-color temperature @tier_dark;\n'
        printf '@define-color memory      @tier_mid;\n'
        printf '@define-color cpu         @tier_light;\n'
        printf '@define-color time        @tier_light;\n'
        printf '@define-color date        @tier_mid;\n'
        printf '@define-color tray        @tier_dark;\n'
        printf '@define-color volume      @tier_dark;\n'
        printf '@define-color backlight   @tier_mid;\n'
        printf '@define-color battery     @tier_light;\n'
        printf '\n/* states */\n'
        printf '@define-color warning  #%s;\n' $P_base0A
        printf '@define-color critical #%s;\n' $P_base08
        printf '@define-color charging #%s;\n' $P_base0B
    end >$f
end

function render_mako
    set -l f "$CFG/mako/config"
    test -f $f; or return
    awk -v bg="#$P_base00" -v fg="#$P_base05" -v br="#$P_base03" \
        -v acc="#$P_base0D" -v urg="#$P_base08" '
      /^\[/ { section=$0 }
      {
        if (section ~ /urgency=high/) {
          if ($0 ~ /^border-color=/) { print "border-color=" urg; next }
          if ($0 ~ /^text-color=/)   { print "text-color=" urg; next }
        } else {
          if ($0 ~ /^background-color=/) { print "background-color=" bg; next }
          if ($0 ~ /^text-color=/)       { print "text-color=" fg; next }
          if ($0 ~ /^border-color=/)      { print "border-color=" br; next }
          if ($0 ~ /^progress-color=/)    { print "progress-color=over " acc; next }
        }
        print
      }
    ' $f >$f.tmp
    mv $f.tmp $f
end

function render_gtk
    set -l dark 1
    test "$P_mode" = light; and set dark 0
    for d in gtk-3.0 gtk-4.0
        set -l s "$CFG/$d/settings.ini"
        test -f $s; or continue
        if grep -q '^gtk-application-prefer-dark-theme=' $s
            sed -i "s/^gtk-application-prefer-dark-theme=.*/gtk-application-prefer-dark-theme=$dark/" $s
        else
            printf 'gtk-application-prefer-dark-theme=%s\n' $dark >>$s
        end
    end
    # libadwaita / GTK color overrides
    set -l block "\
/* >>> theme-manager >>> */
@define-color accent_color #$P_base0D;
@define-color accent_bg_color #$P_base0D;
@define-color accent_fg_color #$P_base00;
@define-color window_bg_color #$P_base00;
@define-color window_fg_color #$P_base05;
@define-color view_bg_color #$P_base00;
@define-color view_fg_color #$P_base05;
@define-color headerbar_bg_color #$P_base01;
@define-color headerbar_fg_color #$P_base05;
@define-color card_bg_color #$P_base01;
@define-color popover_bg_color #$P_base01;
@define-color sidebar_bg_color #$P_base01;
@define-color theme_bg_color #$P_base00;
@define-color theme_fg_color #$P_base05;
@define-color theme_selected_bg_color #$P_base0D;
@define-color theme_selected_fg_color #$P_base00;
/* <<< theme-manager <<< */"
    for d in gtk-3.0 gtk-4.0
        set -l c "$CFG/$d/gtk.css"
        touch $c
        awk '
          /\/\* >>> theme-manager >>> \*\// {skip=1}
          skip==0 {print}
          /\/\* <<< theme-manager <<< \*\// {skip=0}
        ' $c | string collect | string trim -r >$c.tmp
        printf '\n%s\n' "$block" >>$c.tmp
        mv $c.tmp $c
    end
end

function render_qt
    # build a QPalette color-scheme .conf for qt5ct/qt6ct
    # role order matches QPalette::ColorRole (0..20)
    set -l active WindowText:$P_base05 Button:$P_base01 Light:$P_base02 \
        Midlight:$P_base02 Dark:$P_base00 Mid:$P_base01 Text:$P_base05 \
        BrightText:$P_base06 ButtonText:$P_base05 Base:$P_base00 \
        Window:$P_base00 Shadow:000000 Highlight:$P_base0D \
        HighlightedText:$P_base00 Link:$P_base0D LinkVisited:$P_base0E \
        AlternateBase:$P_base01 NoRole:$P_base00 ToolTipBase:$P_base01 \
        ToolTipText:$P_base05 PlaceholderText:$P_base04
    set -l disabled WindowText:$P_base03 Button:$P_base01 Light:$P_base02 \
        Midlight:$P_base02 Dark:$P_base00 Mid:$P_base01 Text:$P_base03 \
        BrightText:$P_base06 ButtonText:$P_base03 Base:$P_base00 \
        Window:$P_base00 Shadow:000000 Highlight:$P_base02 \
        HighlightedText:$P_base03 Link:$P_base0D LinkVisited:$P_base0E \
        AlternateBase:$P_base01 NoRole:$P_base00 ToolTipBase:$P_base01 \
        ToolTipText:$P_base05 PlaceholderText:$P_base04
    set -l a; for e in $active; set -a a "#ff"(string split ':' $e)[2]; end
    set -l d; for e in $disabled; set -a d "#ff"(string split ':' $e)[2]; end
    set -l a_line (string join ', ' $a)
    set -l d_line (string join ', ' $d)
    for qt in qt5ct qt6ct
        set -l dir "$CFG/$qt/colors"
        set -l conf "$CFG/$qt/$qt.conf"
        test -f $conf; or continue
        mkdir -p $dir
        printf '[ColorScheme]\nactive_colors=%s\ninactive_colors=%s\ndisabled_colors=%s\n' \
            "$a_line" "$a_line" "$d_line" >"$dir/theme-manager.conf"
        set -l path "$HOME/.config/$qt/colors/theme-manager.conf"
        if grep -q '^color_scheme_path=' $conf
            sed -i "s|^color_scheme_path=.*|color_scheme_path=$path|" $conf
        else
            sed -i "/^\[Appearance\]/a color_scheme_path=$path" $conf
        end
        grep -q '^custom_palette=' $conf; and sed -i 's/^custom_palette=.*/custom_palette=true/' $conf
    end
end

function render_vscode
    set -l s "$CFG/Code/User/settings.json"
    test -f $s; or return
    command -v jq >/dev/null; or return
    # chrome surface: a bit lighter than the editor in dark mode (so the bars
    # aren't near-black), a bit darker in light mode.
    set -l cf 1.5
    test "$P_mode" = light; and set cf 0.94
    set -l surf (shade_hex $P_base00 $cf)
    set -l tmp (mktemp)
    begin
        printf '{'
        printf '"editor.background":"#%s",' $P_base00
        printf '"editor.foreground":"#%s",' $P_base05
        printf '"editorCursor.foreground":"#%s",' $P_base05
        printf '"editor.selectionBackground":"#%s",' $P_base02
        printf '"editor.lineHighlightBackground":"#%s",' $P_base01
        printf '"editorLineNumber.foreground":"#%s",' $P_base03
        printf '"editorLineNumber.activeForeground":"#%s",' $P_base04
        printf '"editorWidget.background":"#%s",' $P_base01
        printf '"editorWhitespace.foreground":"#%s",' $P_base02
        printf '"sideBar.background":"#%s",' $surf
        printf '"sideBar.foreground":"#%s",' $P_base05
        printf '"sideBarSectionHeader.background":"#%s",' $surf
        printf '"activityBar.background":"#%s",' $surf
        printf '"activityBar.foreground":"#%s",' $P_base05
        printf '"activityBar.inactiveForeground":"#%s",' $P_base03
        printf '"activityBar.activeBorder":"#%s",' $P_base0D
        printf '"activityBarBadge.background":"#%s",' $P_base0D
        printf '"activityBarBadge.foreground":"#%s",' $P_base00
        printf '"statusBar.background":"#%s",' $surf
        printf '"statusBar.foreground":"#%s",' $P_base05
        printf '"statusBar.noFolderBackground":"#%s",' $surf
        printf '"statusBar.debuggingBackground":"#%s",' $P_base0A
        printf '"titleBar.activeBackground":"#%s",' $surf
        printf '"titleBar.activeForeground":"#%s",' $P_base05
        printf '"titleBar.inactiveBackground":"#%s",' $surf
        printf '"titleBar.inactiveForeground":"#%s",' $P_base03
        printf '"tab.activeBackground":"#%s",' $P_base00
        printf '"tab.inactiveBackground":"#%s",' $surf
        printf '"tab.activeForeground":"#%s",' $P_base05
        printf '"tab.inactiveForeground":"#%s",' $P_base04
        printf '"tab.border":"#%s",' $P_base01
        printf '"tab.activeBorderTop":"#%s",' $P_base0D
        printf '"editorGroupHeader.tabsBackground":"#%s",' $surf
        printf '"panel.background":"#%s",' $P_base00
        printf '"panel.border":"#%s",' $P_base02
        printf '"panelTitle.activeForeground":"#%s",' $P_base05
        printf '"terminal.background":"#%s",' $P_base00
        printf '"terminal.foreground":"#%s",' $P_base05
        printf '"terminal.ansiBlack":"#%s",' $P_base00
        printf '"terminal.ansiRed":"#%s",' $P_base08
        printf '"terminal.ansiGreen":"#%s",' $P_base0B
        printf '"terminal.ansiYellow":"#%s",' $P_base0A
        printf '"terminal.ansiBlue":"#%s",' $P_base0D
        printf '"terminal.ansiMagenta":"#%s",' $P_base0E
        printf '"terminal.ansiCyan":"#%s",' $P_base0C
        printf '"terminal.ansiWhite":"#%s",' $P_base05
        printf '"terminal.ansiBrightBlack":"#%s",' $P_base03
        printf '"terminal.ansiBrightRed":"#%s",' $P_base08
        printf '"terminal.ansiBrightGreen":"#%s",' $P_base0B
        printf '"terminal.ansiBrightYellow":"#%s",' $P_base0A
        printf '"terminal.ansiBrightBlue":"#%s",' $P_base0D
        printf '"terminal.ansiBrightMagenta":"#%s",' $P_base0E
        printf '"terminal.ansiBrightCyan":"#%s",' $P_base0C
        printf '"terminal.ansiBrightWhite":"#%s",' $P_base07
        printf '"focusBorder":"#%s",' $P_base0D
        printf '"input.background":"#%s",' $P_base01
        printf '"dropdown.background":"#%s",' $P_base01
        printf '"list.activeSelectionBackground":"#%s",' $P_base02
        printf '"list.activeSelectionForeground":"#%s",' $P_base05
        printf '"list.hoverBackground":"#%s",' $P_base01
        printf '"button.background":"#%s",' $P_base0D
        printf '"button.foreground":"#%s",' $P_base00
        printf '"badge.background":"#%s",' $P_base0D
        printf '"badge.foreground":"#%s"' $P_base00
        printf '}'
    end >$tmp
    jq --slurpfile cc $tmp '. + {"workbench.colorCustomizations": $cc[0]}' $s >$s.tmp
    and mv $s.tmp $s
    rm -f $tmp $s.tmp
end

# ---------------------------------------------------------------------------
# reloads
# ---------------------------------------------------------------------------

# foot 1.27's SIGUSR1/USR2 only switch between the in-memory [colors-dark] /
# [colors-light] sections — they do NOT re-read foot.ini. So to recolor RUNNING
# terminals we push the palette live via OSC escape sequences to each foot pty
# (the pywal trick). New windows read the freshly-written foot.ini at startup.
function reload_foot
    set -l pal $P_base00 $P_base08 $P_base0B $P_base0A $P_base0D $P_base0E $P_base0C $P_base05 \
               $P_base03 $P_base08 $P_base0B $P_base0A $P_base0D $P_base0E $P_base0C $P_base07
    set -l seq (printf '\e]10;#%s\e\\\e]11;#%s\e\\\e]12;#%s\e\\' $P_base05 $P_base00 $P_base05)
    for i in (seq 0 15)
        set seq "$seq"(printf '\e]4;%d;#%s\e\\' $i $pal[(math $i + 1)])
    end
    for fpid in (pgrep -x foot)
        for child in (pgrep -P $fpid)
            set -l tty (ps -o tty= -p $child 2>/dev/null | string trim)
            string match -q 'pts/*' -- $tty; and printf '%s' $seq >/dev/$tty 2>/dev/null
        end
    end
end

function reload_apps
    pkill -USR2 waybar 2>/dev/null
    reload_foot
    command -v makoctl >/dev/null; and makoctl reload 2>/dev/null
    # gtk apps pick up new colors on next launch; nudge running ones via xsettingsd if present
    pkill -HUP xsettingsd 2>/dev/null
    true
end

# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

function cmd_apply --argument-names name
    set -l file "$PALETTE_DIR/$name.conf"
    test -f $file; or set file "$name" # allow a full path
    if not test -f $file
        echo "theme: no such palette '$name'" >&2
        return 1
    end
    load_palette $file
    render_foot
    render_fuzzel
    render_waybar
    render_mako
    render_gtk
    render_qt
    render_vscode
    cp $file "$THEMES_DIR/current.conf"
    echo $P_name >"$THEMES_DIR/current-name"
    reload_apps
    echo "applied: $P_name ($P_mode)"
end

function cmd_matugen --argument-names img
    if not command -v matugen >/dev/null
        echo "theme: matugen not installed (add it to packages.nix and rebuild)" >&2
        return 1
    end
    if test -z "$img"
        # infer current wallpaper from the running wbg process
        set img (string match -rg -- '-s\s+(\S+)' (pgrep -a wbg 2>/dev/null | string join ' '))
        test -z "$img"; and set img (cat "$THEMES_DIR/current-wallpaper" 2>/dev/null)
    end
    if test -z "$img"; or not test -f "$img"
        echo "theme: no image given and no current wallpaper found" >&2
        return 1
    end
    set -l mode dark
    if test -f "$THEMES_DIR/current.conf"
        grep -q '^mode=light' "$THEMES_DIR/current.conf"; and set mode light
    end
    # --prefer is required when run non-interactively (matugen >=4 aborts on
    # ambiguous images otherwise); "saturation" picks the most vivid accent.
    set -l out (matugen image "$img" --mode $mode --prefer saturation 2>&1)
    if test $status -ne 0
        echo "theme: matugen failed:" >&2
        printf '%s\n' $out >&2
        return 1
    end
    if test -f "$PALETTE_DIR/generated.conf"
        sed -i "s/^mode=.*/mode=$mode/" "$PALETTE_DIR/generated.conf"
        cmd_apply generated
    else
        echo "theme: matugen ran but $PALETTE_DIR/generated.conf was not produced (check ~/.config/matugen/config.toml)" >&2
        return 1
    end
end

function cmd_list
    for f in $PALETTE_DIR/*.conf
        basename $f .conf
    end
end

function cmd_current
    cat "$THEMES_DIR/current-name" 2>/dev/null; or echo unknown
end

# ---------------------------------------------------------------------------
# dispatch
# ---------------------------------------------------------------------------

set -l sub $argv[1]
set -l rest $argv[2..-1]
switch "$sub"
    case apply
        cmd_apply $rest
    case matugen
        cmd_matugen $rest
    case list
        cmd_list
    case current
        cmd_current
    case '' help -h --help
        echo "usage: theme.fish {apply <name>|matugen [image]|list|current}"
    case '*'
        echo "theme: unknown command '$sub'" >&2
        exit 1
end
