font_size: 22
theme: void
tree_1:
  google:
    gmail: "https://mail.google.com/"
    calendar: "https://calendar.google.com/"
    maps: "https://maps.google.com/"
    sheets: "https://sheets.google.com"
    docs: "https://docs.google.com"
    slides: "https://slides.google.com"
    drive: "https://drive.google.com/"
    translate: "https://translate.google.com/"
  entertainment:
    plex: "https://www.plex.tv/"
    youtube: "https://www.youtube.com/"

tree_2:
  AI:
    chatGPT: "https://chat.openai.com/"
    gemini: "https://gemini.google.com/"
    notebookLM: "https://notebooklm.google.com/"
  college:
    sis: "https://student.msu.edu/psc/ps/EMPLOYEE/SA/c/NUI_FRAMEWORK.PT_LANDINGPAGE.GBL"
    outlook: "https://spartanmail.msu.edu/"
    d2l: "https://d2l.msu.edu/d2l/lp/auth/saml/initiate-login?entityId=http://www.okta.com/exk8au7wid9bEq7Jw357"
    coursicle: "https://www.coursicle.com/msu/"
    LON-CAPA: "https://s2.lite.msu.edu/"
    McGraw:
      - "https://newconnect.mheducation.com/"
      - "mcgraw hill"
    WebWork: "https://webwork2c.math.msu.edu/webwork2/mth_235_ss26_1"

tree_3:
  server:
    proxmox: "https://192.168.1.10:8006/"
    crafty: "https://192.168.1.11:8443/"
    router: "http://192.168.1.1/"
    homeassistant: "http://192.168.1.20:8123/"
  general:
    github: "https://www.github.com/"
    archwiki:
      - "https://archlinux.org/"
      - "arch wiki"
    nix-search: "https://search.nixos.org/packages?channel=unstable&"
    nix wiki: "https://wiki.nixos.org/wiki/NixOS_Wiki"
  new:
    sheets: "https://www.sheets.new/"
    docs: "https://www.docs.new/"
    slides: "https://www.slides`.new/"
    drawings: "https://www.slides.new/"
