shell=fish
term=xterm-256color

title=foot

font=JetBrainsMono Nerd Font:size=11
letter-spacing=0
dpi-aware=no

pad=25x25

bold-text-in-bright=no

[scrollback]
lines=10000

[cursor]
style=beam
blink=no
beam-thickness=1.5
# underline-thickness=<font underline thickness>

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
clipboard-copy=Control+c
clipboard-paste=Control+v
# primary-paste=Shift+Insert
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
delete-prev-word=Control+BackSpace

[text-bindings]
\x03=Control+Shift+c

[colors]
alpha=0.5
foreground=ffffff
background=000000

regular0=2e3436
regular1=cc0000
regular2=4e9a06
regular3=c4a000
regular4=3465a4
regular5=75507b
regular6=06989a
regular7=d3d7cf
bright0=555753
bright1=ef2929
bright2=8ae234
bright3=fce94f
bright4=729fcf
bright5=ad7fa8
bright6=34e2e2
bright7=eeeeec
