shell=fish
term=xterm-256color

title=foot

font=Dejavu Sans Mono:size=14
letter-spacing=0
dpi-aware=no

pad=25x25

bold-text-in-bright=no

[scrollback]
lines=10000

[cursor]
style=beam
blink=no
beam-thickness=1.5
# underline-thickness=<font underline thickness>

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
clipboard-copy=Control+c
clipboard-paste=Control+v
# primary-paste=Shift+Insert
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
delete-prev-word=Control+BackSpace

[text-bindings]
\x03=Control+Shift+c

[csd]
preferred = none

[colors-dark]
alpha=0.92
foreground=e8e0e8
background=151218
regular0=151218
regular1=ffb4ab
regular2=dab9f9
regular3=d0c1da
regular4=dab9f9
regular5=d0c1da
regular6=f3b7be
regular7=e8e0e8
bright0=2c292e
bright1=ffb4ab
bright2=dab9f9
bright3=d0c1da
bright4=dab9f9
bright5=d0c1da
bright6=f3b7be
bright7=332f35
selection-foreground=e8e0e8
selection-background=221e24

[colors-light]
alpha=0.92
foreground=e8e0e8
background=151218
regular0=151218
regular1=ffb4ab
regular2=dab9f9
regular3=d0c1da
regular4=dab9f9
regular5=d0c1da
regular6=f3b7be
regular7=e8e0e8
bright0=2c292e
bright1=ffb4ab
bright2=dab9f9
bright3=d0c1da
bright4=dab9f9
bright5=d0c1da
bright6=f3b7be
bright7=332f35
selection-foreground=e8e0e8
selection-background=221e24
